from .cpu import CPU
from .gpu import GPU
from .clock import Clock
from .cluster import Cluster
from .android import Android
from .disk import Disk
from .camera import Camera
from .audio import Audio
from .thermal import Thermal
from .bus import Bus